import sys

from MCDC.MCDC_Table import MCDC_Table
from MCDC.LogFile import LogFile

if __name__ == "__main__":
    # Dictionary of MCDC_Table
    d = dict()
    # Log file generated by CPN Tool
    log = LogFile(filename=sys.argv[1])
    for row in log.read_line():
        filtered_row = log.filter_line(row)
        if filtered_row is not None:
            print(filtered_row)
            id_name, truth_values, result = filtered_row
            if id_name not in d.keys():
                d[id_name] = MCDC_Table(id_name)

            d[id_name].update(truth_values, result)

    for key in d:
        print(d[key])
        print(d[key].remaining_conditions())
