python3 CPNExpr_instrument.py ../tests/cpn_models/paxos/paxos.cpn ../tests/cpn_models/paxos/paxos_script_instr.cpn
python3 CPNExpr_instrument.py ../tests/cpn_models/cpnabs/cpnabs.cpn ../tests/cpn_models/cpnabs/cpnabs_script_instr.cpn
python3 CPNExpr_instrument.py ../tests/cpn_models/mqtt/mqtt.cpn ../tests/cpn_models/mqtt/mqtt_script_instr.cpn
python3 CPNExpr_instrument.py ../tests/cpn_models/discspcpn/DisCSPC208WCSsggc.cpn ../tests/cpn_models/discspcpn/discspcpn_script_instr.cpn
python3 CPNExpr_instrument.py ../tests/cpn_models/NatCPN/NPP.cpn ../tests/cpn_models/NatCPN/NPP_script_instr.cpn
python3 CPNExpr_instrument.py ../tests/cpn_models/NatCPN/PC.cpn ../tests/cpn_models/NatCPN/PC_script_instr.cpn
python3 CPNExpr_instrument.py ../tests/cpn_models/NatCPN/TIS.cpn ../tests/cpn_models/NatCPN/TIS_script_instr.cpn
python3 CPNExpr_instrument.py ../tests/cpn_models/NatCPN/VM.cpn ../tests/cpn_models/NatCPN/VM_script_instr.cpn
python3 CPNExpr_instrument.py ../tests/cpn_models/NikiT34-CPN-Model/T34PIM.cpn ../tests/cpn_models/NikiT34-CPN-Model/T34PIM_script_instr.cpn
python3 CPNExpr_instrument.py ../tests/cpn_models/discspcpn/DisCSPC206SBT.cpn ../tests/cpn_models/discspcpn/discspcpnSBT_script_instr.cpn
python3 CPNExpr_instrument.py ../tests/cpn_models/discspcpn/DisCSPC208ABT.cpn ../tests/cpn_models/discspcpn/discspcpnABT_script_instr.cpn